sudo: required
services:
   - docker

before_install:
   - openssl aes-256-cbc -K $encrypted_2685403ab8b4_key -iv $encrypted_2685403ab8b4_iv -in fibonacci-k8s-system-f7765256f603.json.enc -out fibonacci-k8s-system-f7765256f603.json -d
   - curl https://sdk.cloud.google.com | bash > /dev/null;
   - source $HOME/google-cloud-sdk/path.bash.inc
   - gcloud components update kubectl
   - gcloud auth activate-service-account --key-file service-account.json