sudo: required
services:
   - docker

before_install: 
   - docker build -t cspalevic/react-test -f ./client/Dockerfile.dev ./client

script:
   - docker run cspalevic/react-test npm test -- --coverage

after_success:
   - docker build -t cspalevic/multi-client ./client
   - docker build -t cspalevic/multi-nginx ./nginx
   - docker build -t cspalevic/multi-api ./api
   - docker build -t cspalevic/multi-worker ./worker
   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
   - docker push cspalevic/multi-client
   - docker push cspalevic/multi-nginx
   - docker push cspalevic/multi-api
   - docker push cspalevic/multi-worker 